-- ============================================================================
-- Migration 021: AOE Pipeline Tables
-- Adds the internal AOE outbound engine tables to the Ops Supabase database.
-- The AOE pipeline now runs inside Hisako Ops — one unified database.
-- ============================================================================

-- Auto-update helper (may already exist from 001_initial.sql)
create or replace function update_aoe_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── 1. aoe_pipeline_leads ────────────────────────────────────────────────────
-- Raw lead pipeline table. Each row moves through status states.
create table if not exists public.aoe_pipeline_leads (
  id                      uuid primary key default gen_random_uuid(),
  company_name            text not null,
  company_url             text not null,
  contact_email           text,
  contact_name            text,
  contact_title           text,
  status                  text not null default 'PENDING'
    check (status in (
      'PENDING', 'ENRICHING', 'ENRICHED',
      'QUALIFYING', 'QUALIFIED', 'DISQUALIFIED',
      'DRAFTING', 'DRAFTED', 'PUSHED_TO_OPS'
    )),
  enrichment_data         jsonb,
  strategic_hook          text,
  primary_pain_point      text,
  disqualification_reason text,
  retry_count             integer not null default 0,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create unique index if not exists aoe_pipeline_leads_company_url_idx on public.aoe_pipeline_leads(company_url);
create index if not exists aoe_pipeline_leads_status_idx on public.aoe_pipeline_leads(status);
create index if not exists aoe_pipeline_leads_created_idx on public.aoe_pipeline_leads(created_at desc);

alter table public.aoe_pipeline_leads disable row level security;

create trigger aoe_pipeline_leads_updated_at
  before update on public.aoe_pipeline_leads
  for each row execute function update_aoe_updated_at();

-- ── 2. icp_config ────────────────────────────────────────────────────────────
-- Single-row table: Ideal Customer Profile. Workers pull this every run.
create table if not exists public.icp_config (
  id                    uuid primary key default gen_random_uuid(),
  is_active             boolean not null default true,
  target_industries     text[] default '{}'::text[],
  excluded_industries   text[] default '{}'::text[],
  min_employee_count    integer,
  max_employee_count    integer,
  target_geographies    text[] default '{}'::text[],
  excluded_keywords     text[] default '{}'::text[],
  icp_description       text,
  service_framework     text,
  updated_at            timestamptz not null default now()
);

comment on table public.icp_config is 'Ideal Customer Profile (single row). Edit via Ops Settings.';
comment on column public.icp_config.icp_description is 'Plain English ICP summary passed to Gemini in Tier 2 qualification.';
comment on column public.icp_config.service_framework is 'Service pitch injected into email drafting prompt.';

alter table public.icp_config disable row level security;

create trigger icp_config_updated_at
  before update on public.icp_config
  for each row execute function update_aoe_updated_at();

-- ── 3. outbound_drafts ───────────────────────────────────────────────────────
-- Stores the 3-email sequence generated by the drafting worker.
create table if not exists public.outbound_drafts (
  id                  uuid primary key default gen_random_uuid(),
  lead_id             uuid not null references public.aoe_pipeline_leads(id) on delete cascade,
  email_1_subject_a   text,
  email_1_subject_b   text,
  email_1_body        text,
  email_2_subject_a   text,
  email_2_subject_b   text,
  email_2_body        text,
  email_3_subject_a   text,
  email_3_subject_b   text,
  email_3_body        text,
  delivery_status     text not null default 'STAGED'
    check (delivery_status in ('STAGED', 'PUSHED', 'FAILED')),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists outbound_drafts_lead_id_idx on public.outbound_drafts(lead_id);

alter table public.outbound_drafts disable row level security;

create trigger outbound_drafts_updated_at
  before update on public.outbound_drafts
  for each row execute function update_aoe_updated_at();

-- ── 4. qualification_logs ────────────────────────────────────────────────────
-- Audit trail for every Tier 1 & Tier 2 qualification check.
create table if not exists public.qualification_logs (
  id                uuid primary key default gen_random_uuid(),
  lead_id           uuid not null references public.aoe_pipeline_leads(id) on delete cascade,
  tier              integer not null check (tier in (1, 2)),
  result            text not null check (result in ('PASS', 'FAIL')),
  reason            text,
  llm_raw_response  jsonb,
  created_at        timestamptz not null default now()
);

create index if not exists qual_logs_lead_id_idx on public.qualification_logs(lead_id);

alter table public.qualification_logs disable row level security;

-- ── 5. error_logs ────────────────────────────────────────────────────────────
-- Centralised error table for all AOE pipeline workers.
create table if not exists public.error_logs (
  id              uuid primary key default gen_random_uuid(),
  lead_id         uuid references public.aoe_pipeline_leads(id) on delete set null,
  worker          text not null
    check (worker in ('INGEST', 'ENRICHMENT', 'QUALIFICATION', 'DRAFTING', 'OPS_PUSH')),
  error_message   text not null,
  error_payload   jsonb,
  resolved        boolean not null default false,
  created_at      timestamptz not null default now()
);

create index if not exists error_logs_lead_id_idx on public.error_logs(lead_id);
create index if not exists error_logs_resolved_idx on public.error_logs(resolved);

alter table public.error_logs disable row level security;
